name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main # Trigger on push events to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: migrate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      # Apply Supabase migrations using the production database URL secret
      - name: Apply Supabase migrations
        run: supabase db push